project_id = "nolmcafkzqwfmpleyfkx"

[functions.enrich-location]
verify_jwt = true

[functions.batch-enrich]
verify_jwt = true

[functions.batch-geocode]
verify_jwt = true

[functions.quick-classify]
verify_jwt = true

[functions.semantic-search]
verify_jwt = true

[functions.druid-search]
verify_jwt = false

[functions.create-test-users]
verify_jwt = false

[functions.fetch-remote-kml]
verify_jwt = false
